### ISSUE TITLE
Struct as input in funtion throws 

### ISSUE THREAD

**Issue by devedse** [Nethereum/Nethereum#577] opened 2019-08-19 15:53 UTC
I wrote a solidity contract that makes use of the ABIEncoderV2 to be able to call a function with a struct as parameter. When I then try to do this the following error pops up:

```
Warning! Error encountered during contract execution [Bad instruction] 
```

## Expected Behavior
I would expect the transaction to succeed

## Current Behavior
```
Warning! Error encountered during contract execution [Bad instruction] 
```
![image](https://user-images.githubusercontent.com/2350015/63279704-c4e34100-c2a9-11e9-8a54-9766f74a26c7.png)

## Possible Solution
N/A

## Steps to Reproduce
I've created a SmartContract on the ropsten network:
https://ropsten.etherscan.io/address/0xea9d52c1a9c13601c56d648b967acea54243ac83

A minimal code sample of the contract:
```
pragma solidity ^0.5.10;
pragma experimental ABIEncoderV2;

contract SignalContract
{
    mapping (address => bool) public AllowedParties;
    address public Owner;

    mapping(address => mapping(uint => AggregatedDataPerCity[])) public Data;

    modifier onlyOwner() {
        require(msg.sender == Owner, 'This call can only made by the Owner');
        _;
    }

    struct AggregatedDataPerCity {
        string Location;

        WebcrawlerData webcrawlerData;
    }

	struct WebcrawlerData {
		uint NumberOfPeople;
	}

    constructor() public {
        Owner = msg.sender;
    }

    function allowAdditionalParty(address party) public onlyOwner {
        AllowedParties[party] = true;
    }

    function submitData(AggregatedDataPerCity[] memory data) public {
        if (AllowedParties[msg.sender] == false) {
            revert('Party is not allowed');
        }

        AggregatedDataPerCity[] memory foundData = Data[msg.sender][block.number];
        if (foundData.length != 0) {
            revert('Data is already filled');
        }

        for (uint i = 0; i < data.length; i++) {
            Data[msg.sender][block.number][i] = data[i];
        }
    }
}
```

The C# code that I use:
```
            var signalContract = new SignalContractService(web3, address);


            var submitDataFunc = new SubmitDataFunction()
            {
                Data = new List<Data>()
                {
                    new Data()
                    {
                        Location = "Test",
                        WebcrawlerData = new WebcrawlerData()
                        {
                            NumberOfPeople = 100,
                            //Some other variables omitted
                        }
                    }
                },
                Gas = 6000000,
                GasPrice = gasPrice
            };

            var rec = await signalContract.SubmitDataRequestAndWaitForReceiptAsync(submitDataFunc);
```

## Context (Environment)
I'm trying to build a solution where I can store lot's of (somewhat) complicated data in. So having structs as an input parameter for a function really helps.

## Detailed Description
N/A

## Possible Implementation
N/A

**Comment by juanfranblanco** [comment] 2019-08-19 16:54
Hi @devedse ,
How are you? Did you code generated the function messages, struct classes ?  At the moment until the Solidity abi provide us the type the workaround is to match the name of the struct to the type. If you didn't, can you post that here? Thanks

**Comment by devedse** [comment] 2019-08-20 13:26
Hi @juanfranblanco ,

Yes I generated the Contracts project using your VSCode extension. The only thing I did afterwards was update the NuGet packages to the latest version.

Classes of interest:

SignalContractService.cs
```
        public Task<TransactionReceipt> SubmitDataRequestAndWaitForReceiptAsync(SubmitDataFunction submitDataFunction, CancellationTokenSource cancellationToken = null)
        {
             return ContractHandler.SendRequestAndWaitForReceiptAsync(submitDataFunction, cancellationToken);
        }
```

SignalContractDefinition:
```
    public partial class SubmitDataFunction : SubmitDataFunctionBase { }

    [Function("submitData")]
    public class SubmitDataFunctionBase : FunctionMessage
    {
        [Parameter("tuple[]", "data", 1)]
        public virtual List<Data> Data { get; set; }
    }
```

Data class:
```
    public partial class Data : DataBase { }

    public class DataBase 
    {
        [Parameter("string", "Location", 1)]
        public virtual string Location { get; set; }
        [Parameter("tuple", "webcrawlerData", 2)]
        public virtual WebcrawlerData WebcrawlerData { get; set; }
    }
```

Webcrawler data:
```
public partial class WebcrawlerData : WebcrawlerDataBase { }

    public class WebcrawlerDataBase 
    {
        [Parameter("uint256", "NumberOfPeople", 1)]
        public virtual BigInteger NumberOfPeople { get; set; }
        [Parameter("uint256", "CountWomen", 2)]
        public virtual BigInteger CountWomen { get; set; }
        [Parameter("uint256", "CountMen", 3)]
        public virtual BigInteger CountMen { get; set; }
        [Parameter("uint256", "CountAgeRange0_15", 4)]
        public virtual BigInteger CountAgeRange0_15 { get; set; }
        [Parameter("uint256", "CountAgeRange16_17", 5)]
        public virtual BigInteger CountAgeRange16_17 { get; set; }
        [Parameter("uint256", "CountAgeRange18_25", 6)]
        public virtual BigInteger CountAgeRange18_25 { get; set; }
        [Parameter("uint256", "CountAgeRange26_35", 7)]
        public virtual BigInteger CountAgeRange26_35 { get; set; }
        [Parameter("uint256", "CountAgeRange36_50", 8)]
        public virtual BigInteger CountAgeRange36_50 { get; set; }
        [Parameter("uint256", "CountAgeRange51_67", 9)]
        public virtual BigInteger CountAgeRange51_67 { get; set; }
        [Parameter("uint256", "CountAgeRange68_100", 10)]
        public virtual BigInteger CountAgeRange68_100 { get; set; }
    }
```

**Comment by juanfranblanco** [comment] 2019-08-27 10:15
@devedse apologies I did not see your response, I have been away. Did you get it sorted? I cannot see any issue (visually) with your code at the moment.

**Comment by devedse** [comment] 2019-08-27 12:22
Hi @juanfranblanco , nope I did not get it resolved. For now I've worked around it by creating different contracts. But ideally I'd still make this scenario work as well.

**Comment by juanfranblanco** [comment] 2019-08-27 12:28
Many thanks, ill have go locally (when I have a second) and see if i can see the issue. Is that your full DataContract Definitions?

**Comment by devedse** [comment] 2019-08-27 12:45
I generated most code, so hopefully you should be able to easily create a solution based on the contract in the first post.

If you can't manage to reproduce the issue, let me know, and I'll see if I have some time to help you on this.

**Comment by juanfranblanco** [comment] 2019-08-27 15:05
I was hoping to tests against ropsten, but yeah i can probably create another integration test. If you look at the  http://playground.nethereum.com the example on structs, it is not very different from yours.

**Comment by juanfranblanco** [comment] 2019-08-27 16:54
@devedse 
The issue is on the assignment of the mapping in solidity.

This smart contract works:

```solidity
pragma solidity ^0.5.10;
pragma experimental ABIEncoderV2;

contract SignalContract
{
    mapping(address => mapping(uint => AggregatedDataPerCity[])) Data;

    AggregatedDataPerCity dataSingle;

    struct AggregatedDataPerCity {
        string Location;
        WebcrawlerData webcrawlerData;
    }

	struct WebcrawlerData {
		uint NumberOfPeople;
	}

    function submitData(AggregatedDataPerCity[] memory aggregatedDataPerCity) public {
        for (uint i = 0; i < aggregatedDataPerCity.length; i++) {
            dataSingle.Location = aggregatedDataPerCity[i].Location;
            dataSingle.webcrawlerData = aggregatedDataPerCity[i].webcrawlerData;
        }
    }

    function submitData2(AggregatedDataPerCity memory aggregatedDataPerCity) public {
        dataSingle.Location = aggregatedDataPerCity.Location;
        dataSingle.webcrawlerData = aggregatedDataPerCity.webcrawlerData;
    }
}

```
With this code:

```csharp
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Threading.Tasks;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.ABI.Model;
using Nethereum.Contracts;
using Nethereum.Web3.Accounts;
using Nethereum.Web3;
using Nethereum.Hex.HexConvertors.Extensions;


public class SmartContracts_Structs
{


//********* CONTRACT DEFINITION  *******

//***Structs just contain the Parameter attributes, same as Function Messages, Events or Deployment messages***//
    public partial class WebcrawlerData : WebcrawlerDataBase { }

    public class WebcrawlerDataBase 
    {
        [Parameter("uint256", "NumberOfPeople", 1)]
        public virtual BigInteger NumberOfPeople { get; set; }
    }


	 public partial class AggregatedDataPerCity : AggregatedDataPerCityBase { }

    public class AggregatedDataPerCityBase 
    {
        [Parameter("string", "Location", 1)]
        public virtual string Location { get; set; }
        [Parameter("tuple", "webcrawlerData", 2)]
        public virtual WebcrawlerData WebcrawlerData { get; set; }
    }

    public partial class SignalContractDeployment : SignalContractDeploymentBase
    {
        public SignalContractDeployment() : base(BYTECODE) { }
        public SignalContractDeployment(string byteCode) : base(byteCode) { }
    }

     public class SignalContractDeploymentBase : ContractDeploymentMessage
    {
        public static string BYTECODE = "608060405234801561001057600080fd5b50610424806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80636e9feb2c1461003b578063f3acdd3414610050575b600080fd5b61004e6100493660046102dc565b610063565b005b61004e61005e366004610319565b6100c3565b60005b81518110156100bf5781818151811061007b57fe5b6020908102919091018101515180516100989260019201906100e4565b508181815181106100a557fe5b602090810291909101810151015151600255600101610066565b5050565b805180516100d9916001916020909101906100e4565b506020015151600255565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061012557805160ff1916838001178555610152565b82800160010185558215610152579182015b82811115610152578251825591602001919060010190610137565b5061015e929150610162565b5090565b61017c91905b8082111561015e5760008155600101610168565b90565b600082601f83011261019057600080fd5b81356101a361019e82610375565b61034e565b81815260209384019390925082018360005b838110156101e157813586016101cb888261023a565b84525060209283019291909101906001016101b5565b5050505092915050565b600082601f8301126101fc57600080fd5b813561020a61019e82610396565b9150808252602083016020830185838301111561022657600080fd5b6102318382846103be565b50505092915050565b60006040828403121561024c57600080fd5b610256604061034e565b9050813567ffffffffffffffff81111561026f57600080fd5b61027b848285016101eb565b825250602061028c84848301610298565b60208301525092915050565b6000602082840312156102aa57600080fd5b6102b4602061034e565b905060006102c284846102cb565b82525092915050565b80356102d6816103ca565b92915050565b6000602082840312156102ee57600080fd5b813567ffffffffffffffff81111561030557600080fd5b6103118482850161017f565b949350505050565b60006020828403121561032b57600080fd5b813567ffffffffffffffff81111561034257600080fd5b6103118482850161023a565b60405181810167ffffffffffffffff8111828210171561036d57600080fd5b604052919050565b600067ffffffffffffffff82111561038c57600080fd5b5060209081020190565b600067ffffffffffffffff8211156103ad57600080fd5b506020601f91909101601f19160190565b82818337506000910152565b6103d38161017c565b81146103de57600080fd5b5056fea365627a7a7231582026566a769decfaaa68b36927b38cf1fe5fc7338796b6f3e03c548dab572ad7266c6578706572696d656e74616cf564736f6c634300050b0040";
        public SignalContractDeploymentBase() : base(BYTECODE) { }
        public SignalContractDeploymentBase(string byteCode) : base(byteCode) { }

    }

    public partial class SubmitDataFunction : SubmitDataFunctionBase { }

    [Function("submitData")]
    public class SubmitDataFunctionBase : FunctionMessage
    {
        [Parameter("tuple[]", "aggregatedDataPerCity", 1)]
        public virtual List<AggregatedDataPerCity> AggregatedDataPerCity { get; set; }
    }

    public partial class SubmitData2Function : SubmitData2FunctionBase { }

    [Function("submitData2")]
    public class SubmitData2FunctionBase : FunctionMessage
    {
        [Parameter("tuple", "aggregatedDataPerCity", 1)]
        public virtual AggregatedDataPerCity AggregatedDataPerCity { get; set; }
    }
//**** END CONTRACT DEFINITIONS ***** ///

///*** THE MAIN PROGRAM ***
		public static async Task Main()
		{    

// ### Instantiating Web3 and the Account
// To create an instance of web3 we first provide the url of our testchain and the private key of our account. 
// Here we are using http://testchain.nethereum.com:8545 which is our simple single node Nethereum testchain.
// When providing an Account instantiated with a  private key, all our transactions will be signed by Nethereum.

				var url = "http://testchain.nethereum.com:8545";
				var privateKey = "0xb5b1870957d373ef0eeffecc6e4812c0fd08f554b37b233526acc331bf1544f7";
				var account = new Account(privateKey);
				var web3 = new Web3(account, url);

// **** DEPLOYING THE SMART CONTRACT
			 var deploymentReceipt = await web3.Eth.GetContractDeploymentHandler<SignalContractDeployment>()
                .SendRequestAndWaitForReceiptAsync();

					var data = new List<AggregatedDataPerCity>()
                {
                    new AggregatedDataPerCity()
                    {
                        Location = "Test",
                        WebcrawlerData = new WebcrawlerData()
                        {
                            NumberOfPeople = 100,
                        }
                    }
                };


            var contractHandler = web3.Eth.GetContractHandler(deploymentReceipt.ContractAddress);

						var receiptSending = await contractHandler.SendRequestAndWaitForReceiptAsync(
							new SubmitDataFunction() { AggregatedDataPerCity = data });

					Console.WriteLine(receiptSending.HasErrors());
    }

}

```
Just ran that on the playground

**Comment by juanfranblanco** [comment] 2019-08-27 17:28
As a solution you can do this, mainly i am using another mapping to create the indexer of the array and be able to get hold of the storage struct.

```solidity
pragma solidity ^0.5.10;
pragma experimental ABIEncoderV2;

contract SignalContract
{
    mapping(address => mapping(uint => mapping(uint => AggregatedDataPerCity))) Data;

    AggregatedDataPerCity dataSingle;

    struct AggregatedDataPerCity {
        string Location;
        WebcrawlerData webcrawlerData;
    }

	struct WebcrawlerData {
		uint NumberOfPeople;
	}

    function submitData(AggregatedDataPerCity[] memory aggregatedDataPerCity) public {
        for (uint i = 0; i < aggregatedDataPerCity.length; i++) {

            AggregatedDataPerCity storage aggregatedDataPerCityTemp = Data[msg.sender][block.number][i];
            aggregatedDataPerCityTemp.Location = aggregatedDataPerCity[i].Location;
            aggregatedDataPerCityTemp.webcrawlerData = aggregatedDataPerCity[i].webcrawlerData;
        }
    }

    function submitData2(AggregatedDataPerCity memory aggregatedDataPerCity) public {
        dataSingle.Location = aggregatedDataPerCity.Location;
        dataSingle.webcrawlerData = aggregatedDataPerCity.webcrawlerData;
    }
}

```

```csharp
using System;
using System.Collections.Generic;
using System.Numerics;
using System.Threading.Tasks;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.ABI.Model;
using Nethereum.Contracts;
using Nethereum.Web3.Accounts;
using Nethereum.Web3;
using Nethereum.Hex.HexConvertors.Extensions;


public class SmartContracts_Structs
{
    public partial class WebcrawlerData : WebcrawlerDataBase { }

    public class WebcrawlerDataBase 
    {
        [Parameter("uint256", "NumberOfPeople", 1)]
        public virtual BigInteger NumberOfPeople { get; set; }
    }

    public partial class AggregatedDataPerCity : AggregatedDataPerCityBase { }
    public class AggregatedDataPerCityBase 
    {
        [Parameter("string", "Location", 1)]
        public virtual string Location { get; set; }
        [Parameter("tuple", "webcrawlerData", 2)]
        public virtual WebcrawlerData WebcrawlerData { get; set; }
    }

    public partial class SignalContractDeployment : SignalContractDeploymentBase
    {
        public SignalContractDeployment() : base(BYTECODE) { }
        public SignalContractDeployment(string byteCode) : base(byteCode) { }
    }

        public class SignalContractDeploymentBase : ContractDeploymentMessage
    {
        public static string BYTECODE = "608060405234801561001057600080fd5b50610446806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80636e9feb2c1461003b578063f3acdd3414610050575b600080fd5b61004e6100493660046102fe565b610063565b005b61004e61005e36600461033b565b6100e5565b60005b81518110156100e1573360009081526020818152604080832043845282528083208484529091529020825183908390811061009d57fe5b6020908102919091018101515180516100b99284920190610106565b508282815181106100c657fe5b60209081029190910181015101515160019182015501610066565b5050565b805180516100fb91600191602090910190610106565b506020015151600255565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061014757805160ff1916838001178555610174565b82800160010185558215610174579182015b82811115610174578251825591602001919060010190610159565b50610180929150610184565b5090565b61019e91905b80821115610180576000815560010161018a565b90565b600082601f8301126101b257600080fd5b81356101c56101c082610397565b610370565b81815260209384019390925082018360005b8381101561020357813586016101ed888261025c565b84525060209283019291909101906001016101d7565b5050505092915050565b600082601f83011261021e57600080fd5b813561022c6101c0826103b8565b9150808252602083016020830185838301111561024857600080fd5b6102538382846103e0565b50505092915050565b60006040828403121561026e57600080fd5b6102786040610370565b9050813567ffffffffffffffff81111561029157600080fd5b61029d8482850161020d565b82525060206102ae848483016102ba565b60208301525092915050565b6000602082840312156102cc57600080fd5b6102d66020610370565b905060006102e484846102ed565b82525092915050565b80356102f8816103ec565b92915050565b60006020828403121561031057600080fd5b813567ffffffffffffffff81111561032757600080fd5b610333848285016101a1565b949350505050565b60006020828403121561034d57600080fd5b813567ffffffffffffffff81111561036457600080fd5b6103338482850161025c565b60405181810167ffffffffffffffff8111828210171561038f57600080fd5b604052919050565b600067ffffffffffffffff8211156103ae57600080fd5b5060209081020190565b600067ffffffffffffffff8211156103cf57600080fd5b506020601f91909101601f19160190565b82818337506000910152565b6103f58161019e565b811461040057600080fd5b5056fea365627a7a72315820903046564a17321443d0887869adc9bbebc8b83b51853ef42887c32c8c6ccb9b6c6578706572696d656e74616cf564736f6c634300050b0040";
        public SignalContractDeploymentBase() : base(BYTECODE) { }
        public SignalContractDeploymentBase(string byteCode) : base(byteCode) { }

    }

    public partial class SubmitDataFunction : SubmitDataFunctionBase { }

    [Function("submitData")]
    public class SubmitDataFunctionBase : FunctionMessage
    {
        [Parameter("tuple[]", "aggregatedDataPerCity", 1)]
        public virtual List<AggregatedDataPerCity> AggregatedDataPerCity { get; set; }
    }

    public partial class SubmitData2Function : SubmitData2FunctionBase { }

    [Function("submitData2")]
    public class SubmitData2FunctionBase : FunctionMessage
    {
        [Parameter("tuple", "aggregatedDataPerCity", 1)]
        public virtual AggregatedDataPerCity AggregatedDataPerCity { get; set; }
    }
//**** END CONTRACT DEFINITIONS ***** ///

///*** THE MAIN PROGRAM ***
        public static async Task Main()
	{    

		var url = "http://testchain.nethereum.com:8545";
		var privateKey = "0xb5b1870957d373ef0eeffecc6e4812c0fd08f554b37b233526acc331bf1544f7";
		var account = new Account(privateKey);
		var web3 = new Web3(account, url);

// **** DEPLOYING THE SMART CONTRACT
		var deploymentReceipt = await web3.Eth.GetContractDeploymentHandler<SignalContractDeployment>()
                .SendRequestAndWaitForReceiptAsync();

		var data = new List<AggregatedDataPerCity>()
                {
                    new AggregatedDataPerCity()
                    {
                        Location = "Test",
                        WebcrawlerData = new WebcrawlerData()
                        {
                            NumberOfPeople = 100,
                        }
                    },
		   new AggregatedDataPerCity()
                    {
                        Location = "Test2",
                        WebcrawlerData = new WebcrawlerData()
                        {
                            NumberOfPeople = 101,
                        }
                    }
                };

            var contractHandler = web3.Eth.GetContractHandler(deploymentReceipt.ContractAddress);

	    var receiptSending = await contractHandler.SendRequestAndWaitForReceiptAsync(
							new SubmitDataFunction() { AggregatedDataPerCity = data });

	Console.WriteLine(receiptSending.HasErrors());
    }
}

```

**Comment by juanfranblanco** [comment] 2019-08-27 17:30
I am closing this now, let me know if you have any issues (gitter best ;) )

**Closed by juanfranblanco** 2019-08-27 17:30 UTC
