### ISSUE TITLE
RPC Client stop working without any changes in the code

### ISSUE THREAD

**Issue by paykap** [Nethereum/Nethereum#395] opened 2018-08-01 16:02 UTC
Our app was working fine, but suddenly we are getting an error while checking the token account balance.
Error : 
Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult) at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult) --- End of inner exception stack trace --- at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult) at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult) at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context) at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar) --- End of inner exception stack trace --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at Nethereum.JsonRpc.Client.RpcClient.<SendAsync>d__17.MoveNext() --- End of inner exception stack trace --- at Nethereum.JsonRpc.Client.RpcClient.<SendAsync>d__17.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at Nethereum.JsonRpc.Client.RpcClient.<SendInnerRequestAync>d__12`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at Nethereum.JsonRpc.Client.ClientBase.<SendRequestAsync>d__4`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() at Nethereum.Contracts.FunctionBase.<CallAsync>d__17`1.MoveNext()

Can you help with what happened?

**Comment by juanfranblanco** [comment] 2018-08-02 16:29
Are you using infura? And .net451?

**Comment by paykap** [comment] 2018-08-02 19:09
yes please

**Comment by juanfranblanco** [comment] 2018-08-02 20:28
Use this setting https://github.com/Nethereum/Nethereum.CQS.SimpleTokenTransfer/blob/master/Nethereum.CQS.SimpleTokenTransfer.Net451/Program.cs#L21

**Comment by paykap** [comment] 2018-08-02 22:08
Thanks very much for your help. 

Our smart contract was already deployed and was working fine: 1- transferring token from our app (1178 transfers from our app), 2- checking the token balance of the client from our app, 

but suddenly we are getting an error while trying to check balance or to transfer tokens without any change on our app.

**Error message**: Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s). The underlying connection was closed: An unexpected error occurred on a send. 

we are using mainnet.infura.io/our_key and .net451.

**Comment by juanfranblanco** [comment] 2018-09-18 08:31
Closing the issue is the TSL2 + net451

**Closed by juanfranblanco** 2018-09-18 08:31 UTC
