### ISSUE TITLE
Smart Contract Deployment Sample gives exceed block gas limit error always

### ISSUE THREAD

**Issue by aamolgote** [Nethereum/Nethereum#368] opened 2018-06-26 16:46 UTC
I am using the sample from this link https://github.com/Nethereum/Nethereum/blob/master/src/Nethereum.Tutorials/Nethereum.Tutorials/Deployment/Deployment.cs
to deploy same test contract of multiply but when I run this on my private chain I am always getting this error 
"Nethereum.JsonRpc.Client.RpcResponseException: exceeds block gas limit"
I have tried various options on setting gas limit with various combination still the same issue.

When I deploy the contract through GETH console same contract every thing works fine, issue is coming when I do it from nethereum Nuget package. I have converted your test method to console app and testing on private chain.

Here is my genesis.json for private chain
{
    "alloc": {
        "bf28300bdda3293c33294b114b2d1d9c2ac89458": {
            "balance": "10000000000000000000"
        }
    },
    "config": {
        "chainID": 91,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "nonce": "0x0000000000000000",
    "difficulty": "0x0008",
    "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
    "gasLimit": "3141592000000"
}

**Comment by juanfranblanco** [comment] 2018-06-27 11:38
Hi,

I have upgraded (latest Nethereum, not that it should have been a problem) and tested this with the geth test chain and no issues. 

This might help you:
https://github.com/Nethereum/TestChains/blob/master/geth-clique-windows/genesis_clique.json

**Comment by aamolgote** [comment] 2018-06-27 13:18
I tried using the "https://github.com/Nethereum/TestChains/blob/master/geth-clique-windows/genesis_clique.json" file for setting up my chain, but I am still seeing the same error
This is how my package.config looks like
<packages>
  <package id="BouncyCastle" version="1.8.2" targetFramework="net461" />
  <package id="Common.Logging.Core" version="3.4.1" targetFramework="net461" />
  <package id="Nethereum.ABI" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Accounts" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Contracts" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Geth" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Hex" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.JsonRpc.Client" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.JsonRpc.RpcClient" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.KeyStore" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.RLP" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.RPC" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Signer" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Util" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Web3" version="2.5.1" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net461" />
</packages>

And below is my code snippet for console app
public async Task ExecuteContract()
        {
            var senderAddress = "0x12890d2cce102216644c59dae5baed380d84830c";
            var password = "password";


            //senderAddress = "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1";
            //password = "4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d";

            var abi = @"[{'constant':false,'inputs':[{'name':'val','type':'int256'}],'name':'multiply','outputs':[{'name':'d','type':'int256'}],'payable':false,'stateMutability':'nonpayable','type':'function'},{'inputs':[{'name':'multiplier','type':'int256'}],'payable':false,'stateMutability':'nonpayable','type':'constructor'}]";
            var byteCode =
                "0x608060405234801561001057600080fd5b5060405160208061013f83398101806040528101908080519060200190929190505050806000819055505060f6806100496000396000f3006080604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063c6888fa114604e578063f404f43414608c575b600080fd5b348015605957600080fd5b5060766004803603810190808035906020019092919050505060b4565b6040518082815260200191505060405180910390f35b348015609757600080fd5b50609e60c1565b6040518082815260200191505060405180910390f35b6000805482029050919050565b600060409050905600a165627a7a72305820fe16756c8e092da2aa2d850473a7fa8ec660e7ae7631dbd8191ee637a65020ff0029";

            var multiplier = 7;

            //a managed account uses personal_sendTransanction with the given password, this way we don't need to unlock the account for a certain period of time
            var account = new ManagedAccount(senderAddress, password);

            //using the specific geth web3 library to allow us manage the mining.
            var web3 = new Nethereum.Geth.Web3Geth(account);
            

            var unlockAccountResult = web3.Personal.UnlockAccount.SendRequestAsync(senderAddress, password, 120).Result;
            Console.WriteLine("Unlock account Status: " + unlockAccountResult);

            // start mining
            //await web3.Miner.Start.SendRequestAsync(1);

            var receipt =
                await web3.Eth.DeployContract.SendRequestAsync(abi, byteCode, senderAddress, new HexBigInteger(900000), null, multiplier);

            //var mineResult = await web3.Miner.Stop.SendRequestAsync();
            //Console.WriteLine(mineResult);

            var contractAddress = receipt;

            var contract = web3.Eth.GetContract(abi, contractAddress);

            var multiplyFunction = contract.GetFunction("multiply");

            var result = await multiplyFunction.CallAsync<int>(7);

            Console.WriteLine(result);

        }

I have tried with by un-commenting mining Line of code....

**Comment by aamolgote** [comment] 2018-06-27 13:19
Package.config
<packages>
  <package id="BouncyCastle" version="1.8.2" targetFramework="net461" />
  <package id="Common.Logging.Core" version="3.4.1" targetFramework="net461" />
  <package id="Nethereum.ABI" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Accounts" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Contracts" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Geth" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Hex" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.JsonRpc.Client" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.JsonRpc.RpcClient" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.KeyStore" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.RLP" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.RPC" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Signer" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Util" version="2.5.1" targetFramework="net461" />
  <package id="Nethereum.Web3" version="2.5.1" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net461" />
</packages>

**Comment by aamolgote** [comment] 2018-06-27 13:20
[packages - Copy.config.txt](https://github.com/Nethereum/Nethereum/files/2141373/packages.-.Copy.config.txt)

**Comment by juanfranblanco** [comment] 2019-03-06 12:09
Closing this now, as I could not reproduced it (a while ago) Please come to gitter if you are still stuck.

**Closed by juanfranblanco** 2019-03-06 12:09 UTC
