### ISSUE TITLE
Calling any RPC method to geth throws exception due to json rpc missing 'id'

### ISSUE THREAD

**Issue by slothbag** [Nethereum/Nethereum#3] opened 2016-02-27 14:18 UTC
Error:
`Message	"Required property 'id' not found in JSON. Path '', line 1, position 111."	string`

My gut feeling is geth is not returning a valid rpc response (missing the id), but i'm not sure where its going wrong.

(i tried latest commit, still not working for me)

**Comment by juanfranblanco** [comment] 2016-02-27 22:25
Can you post some code to investigate?

**Comment by slothbag** [comment] 2016-02-27 22:44
So this code throws same error

`var web3 = new Web3();
var result = web3.Eth.GetBalance.SendRequestAsync("0x72e27d0e19f1e57f6764bb6670759f52abca4294");
while (!result.IsCompleted)
   System.Threading.Thread.Sleep(100);`

**Comment by slothbag** [comment] 2016-02-27 23:05
Ok, with the help of wireshark I can see the JSON messages..

The request
`{"id":"1","jsonrpc":"2.0","method":"net_peerCount","params":[null]}`

The response
`{"jsonrpc":"2.0","error":{"code":-32700,"message":"json: cannot unmarshal string into Go value of type int64"}}`

**Comment by slothbag** [comment] 2016-02-28 00:03
I can confirm, sending "id":"1" via curl results in same error, however passing "id":1 works.

**Comment by juanfranblanco** [comment] 2016-02-28 07:05
It seems you are using a different version of geth, I am targeting currently stable 3.3. The current version accepts the string. Which version are you using? I assume newer than 3.3, so I will do the fix.

**Comment by slothbag** [comment] 2016-02-28 07:20
I'm using latest nightly builds, v4 I think.

**Comment by juanfranblanco** [comment] 2016-02-28 07:26
Thanks, the issue is with the rpc library I am using. I have created a pull request https://github.com/Gekctek/JsonRpc.Router/pull/11 to support objects instead.

**Comment by slothbag** [comment] 2016-02-28 07:27
I might raise issue with geth too. Rpc standard says ID as string is permissible

**Comment by juanfranblanco** [comment] 2016-02-28 07:28
Yes good idea

**Comment by slothbag** [comment] 2016-02-29 23:02
I compiled and referenced the new build of Nethereum and referenced the new JsonRpc.Client dlls.. but still the "id" is being sent as a string..

**Comment by juanfranblanco** [comment] 2016-03-01 03:40
Yes I am forcing an string to make it compile, I was awating the release.

**Comment by juanfranblanco** [comment] 2016-03-01 05:19
I have checked in now the fixes, now targets 451 and starts targetting dotnet52, not complete

**Closed** 2016-03-01 05:20 UTC

**Comment by slothbag** [comment] 2016-03-01 09:16
Works great, thanks.

**Comment by juanfranblanco** [comment] 2016-03-01 09:41
:+1:
