### ISSUE TITLE
Transfer ether using smart contract and Nethereum

### ISSUE THREAD

**Issue by haimHadad** [Nethereum/Nethereum#600] opened 2019-11-07 21:19 UTC
I am trying to transfer ether to a contract and from contract to another account. 
So far I succeded to run the solidity code in Remix using javascript VM and injected web3 (contract deployed on Remix+Metamask too).
I succeded to send ether to the contract using Nethereum, but when it comes to triggering the transfer function in Nethereum -> it`s not working (nothing happen). 
Here is the Solidity code :

    `pragma solidity ^0.5.11;
    contract MyFirstContract
    {
        function() external payable { }
            function getBalance() public view returns(uint)
            {
                return address(this).balance;
            }
            
        function send(address payable _to, uint256 _value) public returns (bool) 
        {
           require(_value <= address(this).balance);
           _to.transfer(_value);
           return true;
        }
    } `

And Nethereum code (Infura -Ropsten):

                   `var contractAddress = "0xEf0cFd55488895E63cA368D989405ab348F1BBd7";
                    var transactionHash =    0x14b5678436c492ab468e67ca5ec8356deee566017b1d158491fa92cc35e0b80";
                    var contractABI = @"[ { ... ]";
                    var senderAddressTest = acc.AccountAddress;
                    var recipientAddressTest = "0x7988dfD8E9ceCb888C1AeA7Cb416D44C6160Ef80";
                    var senderPrivateKeyTest = acc.AccountPassword;
                    var accountTest = new Nethereum.Web3.Accounts.Account( senderPrivateKeyTest );
                    var web3Test = new Web3(accountTest , acc.AccountNetwork + "" + acc.InfuraApiKey);
                    var contractTest = web3Test.Eth.GetContract(contractABI, contractAddress);
                    var transaction = await web3Test.Eth.GetEtherTransferService().TransferEtherAndWaitForReceiptAsync(contractAddress, 2.00m, 2, new BigInteger(25000)); //=> This function sends ether to the contract, It worked and confirmed on ropsten.etherscan.io
                    var function = contractTest.GetFunction("send");
                    var wie = 2000000000000000000; // => the ether I want to send from the smart contract for example
                    object[] parameters = new object[2] { recipientAddressTest, wie };
                    var result = await function.CallAsync<bool>(parameters); //==>***
                    //***=> I guess this line initiates the send function, it work on Remix, 
                    //***=>but not in Nethereum. However, the result is true (strange...) 
                    //***=>and recipientAddressTest  doesn`t get ether, etherscan didn`t update too
 
                   `

**Comment by haimHadad** [comment] 2019-11-08 08:44
I also noticed that getBalance doesnt work too:

           `
         var function = contractTest.GetFunction("getBalance");
         var result = await function.CallAsync<uint>();
         `

**Comment by haimHadad** [comment] 2019-11-08 09:29
For your information, the other function works: 

        `
        var function = contractTest.GetFunction("getBalance");
        var result = await function.CallAsync<UInt64>();
        `

**Comment by juanfranblanco** [comment] 2019-11-08 09:41
Hi @haimHadad  for general queries can you come to gitter and everyone can help you https://gitter.im/Nethereum/Nethereum

I can see that you are transferring Ether to the smart contract and you want to transfer it to another address using the solidity send function.

Querying the balance is ok, but transferring does not work.

The issue is that there are two types of interactions with a smart contract (Calls, which you are querying the blockchain, no state changes)
and Transactions (which mainly change the state of the smart contract and the blockchain) 
your "send" function instead of using Call needs to use the method SendTransactionAsync or SendTransactionAndWaitForReceiptAsync

A good example can be found here:
http://playground.nethereum.com/csharp/id/1045

Nevertheless I recommend you using Types vs Untyped as Nethereum has extra functionality to help you.

You can code generate your types using any of our code generators

http://docs.nethereum.com/en/latest/nethereum-code-generation/

Or you can even experiment directly in http://playground.nethereum.com with the Abi Code Gen

**Comment by haimHadad** [comment] 2019-11-08 10:33
It worked! Thank you very much!! 

        `

                    var sendFunction = contractTest.GetFunction("send");

                    var gas = await sendFunction.EstimateGasAsync(senderAddressTest, null, null, recipientAddressTest, wieEtherTest);
                    var receiptAmountSend =await sendFunction.SendTransactionAndWaitForReceiptAsync(senderAddressTest, gas, null, null, recipientAddressTest, wieEtherTest);

        `

**Closed** 2020-01-28 06:33 UTC
