### ISSUE TITLE
System.Net.Sockets.SocketException: No such device or address

### ISSUE THREAD

**Issue by senzacionale** [Nethereum/Nethereum#508] opened 2019-01-27 14:41 UTC
I am having problem with Infura and Nethereum. I have contacted Infura and they have told me that this is Nethereum issue:

> (Inner Exception #0) Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestException: No such device or address ---> System.Net.Sockets.SocketException: No such device or address

or

> ---> (Inner Exception #0) Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.Net.Http.HttpRequestException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use

This is my code which throw this error:
` HexBigInteger blockNumber = await Web3.Eth.Blocks.GetBlockNumber.SendRequestAsync();`

Any idea?

**Comment by senzacionale** [comment] 2019-01-28 08:16
This is my code:

```
public Web3 Web3
        {
            get
            {
                if (_web3 == null)
                {
                    _web3 = new Web3(Account, RpcUrl);
                }

                return _web3;
            }
        }
```


where Account is
```

ublic Account Account
        {
            get
            {
                Wallet wallet =
                    new Wallet("xxx", "");
                var account = new Account(wallet.GetPrivateKey(0));
                return account;
            }
        }
```

**Comment by juanfranblanco** [comment] 2019-01-28 09:07
You should not have any problems, what rpc url are you using? And are you using .net451?

**Comment by senzacionale** [comment] 2019-01-28 10:09
I am using last version of Nethereum and .net CORE. I am using .net CORE 2.2

**Comment by juanfranblanco** [comment] 2019-01-28 15:44
@senzacionale have you tested it using just a simple:

```csharp
var web3 = new Web3("https://mainnet.infurai.io");
var blockNumber = await Web3.Eth.Blocks.GetBlockNumber.SendRequestAsync();
```

**Comment by senzacionale** [comment] 2019-01-28 15:49
I am using already Infura. My RpcUrl is Infura Url

**Comment by juanfranblanco** [comment] 2019-01-28 16:10
Yes I just want to validate why you have the error in simple terms. Mainly it should not fail.

**Comment by senzacionale** [comment] 2019-01-28 19:45
It should not but it fail. I have no idea why. And it fail very often ...

**Comment by juanfranblanco** [comment] 2019-02-04 10:58
hey @senzacionale have you got more info on this? Is there anything on your setup, environment that could be the cause, nobody else has reported anything, but it will be great to figure out the route cause.

**Comment by senzacionale** [comment] 2019-02-04 21:03
I am checking if is related with docker and non SSD disk. Do you suggest using SSD disk?

**Comment by juanfranblanco** [comment] 2019-02-05 09:02
Yes but that should not be an issue, I had a node running on a mechanical drive for a while. Although docker and networking might be the problem.

**Comment by juanfranblanco** [comment] 2019-03-06 18:20
Closing this now..

**Closed by juanfranblanco** 2019-03-06 18:20 UTC
