### ISSUE TITLE
EthECKey truncates first zero-byte of private key

### ISSUE THREAD

**Issue by AndreiMisiukevich** [Nethereum/Nethereum#537] opened 2019-04-08 15:26 UTC
## Expected Behavior
```GetPrivateKeyAsBytes``` should return the same private key as was passed to constructor

## Current Behavior
```GetPrivateKeyAsBytes``` modifies original key and return truncated one (without first zero byte)

## Possible Solution
Store original key and return it

## Detailed Description
Look at next lines of code:

<img width="677" alt="3" src="https://user-images.githubusercontent.com/10124814/55735929-0249df00-5a2b-11e9-9d99-ce2d96e523b2.png">

32 bytes of private key (with seed[0] == 0)
we pass it to ```EthECKey(seed, true)```
then we try to retrieve it ```let privateKeyBytes = privateKey.GetPrivateKeyAsBytes()```

Finally **privateKeyBytes** contains 31 bytes. I presume that's due first byte is 0, because it works fine with other keys.

So, first zero was truncated.

SO, **seed**:
<img width="203" alt="1" src="https://user-images.githubusercontent.com/10124814/55735911-f4945980-5a2a-11e9-9507-051a7bc42e0c.png">

AND **privateKeyBytes**:
<img width="258" alt="2" src="https://user-images.githubusercontent.com/10124814/55736197-82704480-5a2b-11e9-8f1b-7294f348f556.png">

**Comment by knocte** [comment] 2019-04-10 05:17
@AndreiMisiukevich you forgot to mention that this doesn't happen in the same way for all inputs, because it took us a while to reproduce this problem. Please include details of when `GetPrivateKeyAsBytes()` truncates and when it doesn't.

**Comment by juanfranblanco** [comment] 2019-04-10 06:10
This is mainly due to the 0 being the sign of the big integer. What happens is that your private key gets converted into a big integer unsigned so when it returns you the key back it is mainly a 31 byte array. 

Now it will be interesting to see what was the original key generated, did it have 33 bytes and 2 0 prefixes? 

@knocte what tests have you ran ?

**Comment by knocte** [comment] 2019-04-10 06:39
I think the original key that suffered this bug had 32 bytes. Why does it need those prefixes? As I said before, the majority of randomly generated keys don't suffer this problem.

> what tests have you ran?

What do you mean?

**Comment by juanfranblanco** [comment] 2019-04-10 06:55
You mentioned "it took us a while to reproduce it". Hence my question.

My point on 32 Vs 33 is that sometimes keys are generated with 33 bytes as they include the sign. 

This means nothing in reality as the encoding / decoding is the same, as all private keys end up unsigned.

In this scenario we have a 32 bytes key with a 0 prefix, so the sign prefix has been stripped.

**Comment by knocte** [comment] 2019-04-10 07:14
AFAIR all our keys are 32 bytes, not 33 (they are generated by the WarpWallet algorithm).

> In this scenario we have a 32 bytes key with a 0 prefix

Aha, so this is why it took us a while to reproduce: there's 1 chance out of 2^8 that we get a zero as the first byte.

**Comment by juanfranblanco** [comment] 2019-04-10 13:54
@AndreiMisiukevich any chance you can write the hex here?

**Comment by juanfranblanco** [comment] 2019-04-10 13:58
@knocte @AndreiMisiukevich sorry I was being stupid and I just realised you both of you work on the wallet. I am thinking for that scenario, ie 32 bytes with a 0 prefix, to add an extra byte 0 which can be treated as the sign.

**Comment by AndreiMisiukevich** [comment] 2019-04-10 14:01
> @knocte @AndreiMisiukevich sorry I was being stupid and I just realised you both of you work on the wallet. I am thinking for that scenario, ie 32 bytes with a 0 prefix, to add an extra byte 0 which can be treated as the sign.

looks like kind of hack :)

```csharp
if(seed[0] == 0)
{
    //resize array with one more zero
}
```

**Comment by juanfranblanco** [comment] 2019-04-10 14:04
Yeah.. that is exactly the idea :) I just want to unit test it with your current key.

**Comment by AndreiMisiukevich** [comment] 2019-04-10 14:14
@juanfranblanco current key is on the first screenshot)
I think, it doesn't matter what are the other bytes - but first one should be zero

**Comment by juanfranblanco** [comment] 2019-04-10 14:23
yeah that is part of the test, bouncy just uses the first byte.

**Comment by AndreiMisiukevich** [comment] 2019-04-10 14:32
@juanfranblanco maybe it would be better to add any extra parameter, which will manage whether it is "signed" byte array or "unsigned" ?

**Comment by knocte** [comment] 2019-04-10 14:37
Should private keys really have the concept of signed or unsigned? If we were talking about a number, then the ctor would receive a numeric type, not an array of bytes.

**Comment by juanfranblanco** [comment] 2019-04-10 14:38
Well if it is 32 bytes which is the expected length of a private key, it should be fine. Actually the input for to bouncy it always specifies as a positive big integer.

**Comment by juanfranblanco** [comment] 2019-04-10 14:39
@knocte Yes, private keys / public keys are bigintegers as a byte array. Easier to transport the hex values.

**Comment by AndreiMisiukevich** [comment] 2019-04-10 14:41
Hm, in this case, i think, this issue can be closed
maybe it will help anybody in future :) thanks @juanfranblanco

**Comment by juanfranblanco** [comment] 2019-04-10 14:43
More info, on elliptic curve here, just found it, and it seems after skipping thorugh it a rather good explanation. https://hackernoon.com/what-is-the-math-behind-elliptic-curve-cryptography-f61b25253da3

**Comment by juanfranblanco** [comment] 2019-04-10 14:46
@AndreiMisiukevich I don't know, as I actually don't want to strip those zeros even if not relevant as there are places that expect you to have a 32 byte array for your private key.

**Comment by juanfranblanco** [comment] 2019-05-04 11:00
Adding to this, keys generated I might force regeneration when there are a number of 00 bytes either prefixed or suffixed to avoid attacks

**Closed** 2020-02-19 08:40 UTC
